config/routes.rb
Tooltime::Application.routes.draw do
  # misc routes
  get 'main/index'
  
  # analytics
  get "gene_search/index"
  get 'gene_search/search'
  get "popular_factors/index"
  get "popular_factors/search"
  get "popular_factors/results"
  
  # data uploading
  post  'data/upload'
  match "/data/status/:job_id" => "data#status"
  
  # browse comparisons
  resources :comparisons do
    resources :experiments do
      resources :genes, :only => [:show], :controller => 'browse_genes' do
        resources :regulatory_elements, :only => [:show], :controller => 'browse_regulatory_elements'
      end
    end
  end
  
  # db summary: transcription factors
  resources :transcription_factors

  # db summary: genes
  resources :genes

  # db summary: regulatory elements
  resources :regulatory_elements
  
  # main page
  root :to => 'main#index'
end

app/models/comparison.rb
class Comparison < ActiveRecord::Base
  has_many :experiments, :dependent => :destroy
  validates_uniqueness_of :state, :scope => [:species, :cell_type]
  
  # returns unique values of species for all comparisons
  def self.all_species
    self.all.map(&:species).uniq
  end
end

app/controllers/comparisons_controller.rb
class ComparisonsController < ApplicationController
  def index
    @species_opts = Comparison.all_species.map {|s| [s, s]}
    @comparisons  = sorted_collection(filtered_comparisons)
  end
  
  def show
    @comparison  = Comparison.find(params[:id])
    @experiments = sorted_experiments(@comparison.experiments)
  end
  
  def edit
    @comparison = Comparison.find(params[:id])
  end
  
  def update
    comparison = Comparison.find(params[:id])
    comparison.update_attributes(params[:comparison])
    flash[:notice] = 'Comparison updated successfully.'
    redirect_to comparison
  end
  
  private
  
  def filtered_comparisons
    params[:species].nil? ? Comparison.all : Comparison.where(species: params[:species])
  end
  
  def sorted_experiments(experiments)
    if params[:sort] =~ /genes_identified_/ && experiments.size > 1
      i_by = params[:sort].split('_').last
      dir = params[:sort].split('_').last.to_sym
      dir = nil if i_by == 'total'
      if params[:order] == 'asc'
        experiments.sort_by {|a,b| a.identified(dir) <=> b.identified(dir)}
      elsif params[:order] == 'desc'
        experiments.sort_by {|a,b| b.identified(dir) <=> a.identified(dir)}
      end
    elsif params[:sort] =~ /genes_identified_/ && experiments.size <= 1
      experiments
    else
      sorted_collection(experiments)
    end
  end
end

app/helpers/comparisons_helper.rb
module ComparisonsHelper
end

app/views/comparisons/edit.html.erb
<div class="content edit-comparison">
  <div class="row banner">
    <div class="span12">
      <h1>Edit Comparison</h1>
    </div>
  </div>
  <div class="row banner">
    <div class="span12">
      <%= form_for @comparison do |f| %>
        <p>
          <%= f.label :state %>
          <%= f.text_field :state %>
        </p>
        <p>
          <%= f.label :species %>
          <%= f.text_field :species %>
        </p>
        <p>
          <%= f.button :class => 'btn btn-primary' %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/comparisons/index.html.erb
<div class="content browse-comparisons">
  <div class="row banner">
    <div class="span6">
      <h1>Browse Comparisons <small>by species</small></h1>
    </div>
  </div>
  <div class="row">
    <div class="span6">
      <form action="" class="form-horizontal" method="get">
        <fieldset>
          <%= select_tag :species, options_for_select(@species_opts, @selected_species), {:class => 'span2'} %>
          <button type="submit" class="btn">Go</button>
        </fieldset>
      </form>
    </div>
  </div>
  <div class="row">
    <div class="span12">
      <table class="table table-bordered table-striped table-sortable">
        <thead>
          <tr>
            <th width="2%"></th>
            <th><%= sortable_col :state %></th>
            <th><%= sortable_col :species %></th>
          </tr>
        </thead>
        <tbody>
          <% @comparisons.each do |comparison| %>
            <tr>
              <td width="2%"><a class="edit" href="<%= edit_comparison_path comparison %>"><i class="icon-edit"></i></a></td>
              <td><%= link_to(comparison.state, comparison) %></td>
              <td><%= comparison.species %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/comparisons/show.html.erb
<div class="content show-comparison">
  <div class="row banner">
    <div class="span12">
      <h2>Comparison:</h2>
    </div>
  </div>
  <div class="row">
    <div class="span2"><h4>state:</h4></div>
    <div class="span10"><h3><%= @comparison.state %></h3></div>
  </div>
  <div class="row">
    <div class="span2"><h4>species:</h4></div>
    <div class="span10"><h3><%= @comparison.species %></h3></div>
  </div>
  <div class="row banner">
    <div class="span12">
      <h2>Experiments:</h2>
    </div>
  </div>
  <div class="row">
    <div class="span12">
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th width="2%"></th>
            <th><%= sortable_col :label %></th>
            <th><%= sortable_col :genes_identified_total, 'genes identified' %> <span class="label label-info">total</span></th>
            <th><%= sortable_col :genes_identified_up, 'genes identified' %> <span class="label label-info">up regulated</span></th>
            <th><%= sortable_col :genes_identified_down, 'genes identified' %> <span class="label label-info">down regulated</span></th>
          </tr>
        </thead>
        <tbody>
          <% @experiments.each do |exp| %>
            <tr>
              <td width="2%"><a class="edit" href="<%= edit_comparison_experiment_path(@comparison, exp) %>"><i class="icon-edit"></i></a></td>
              <td><%= link_to(exp.label, comparison_experiment_path(@comparison, exp)) %></td>
              <td><%= exp.identified %></td>
              <td><%= exp.identified(:up) %></td>
              <td><%= exp.identified(:down) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>