config/routes.rb
Tooltime::Application.routes.draw do
  # misc routes
  get 'main/index'
  
  # analytics
  get "gene_search/index"
  get 'gene_search/search'
  get "popular_factors/index"
  get "popular_factors/search"
  get "popular_factors/results"
  
  # data uploading
  post  'data/upload'
  match "/data/status/:job_id" => "data#status"
  
  # browse comparisons
  resources :comparisons do
    resources :experiments do
      resources :genes, :only => [:show], :controller => 'browse_genes' do
        resources :regulatory_elements, :only => [:show], :controller => 'browse_regulatory_elements'
      end
    end
  end
  
  # db summary: transcription factors
  resources :transcription_factors

  # db summary: genes
  resources :genes

  # db summary: regulatory elements
  resources :regulatory_elements
  
  # main page
  root :to => 'main#index'
end

app/models/experiment.rb
class Experiment < ActiveRecord::Base
  belongs_to :comparison
  has_many   :genes
  validates_uniqueness_of :label
  
  def identified(regulation=nil)
    if regulation.nil?
      self.genes.size
    elsif regulation == :up
      self.genes.select{|g| g.regulation == 'up'}.size
    elsif regulation == :down
      self.genes.select{|g| g.regulation == 'down'}.size
    end
  end
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  def show
    @comparison = Comparison.find(params[:comparison_id])
    @experiment = Experiment.find(params[:id])
    @genes      = sorted_collection(filtered_genes(@experiment))
  end
  
  def edit
    @experiment = Experiment.find(params[:id])
  end
  
  def update
    experiment = Experiment.find(params[:id])
    experiment.update_attributes(params[:experiment])
    flash[:notice] = 'Experiment updated successfully.'
    redirect_to comparisons_path
  end
  
  private
  
  def filtered_genes(experiment)
    if params[:regulation].nil?
      experiment.genes
    else
      experiment.genes.where(:regulation => params[:regulation])
    end
  end
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/views/experiments/edit.html.erb
<div class="content edit-comparison">
  <div class="row banner">
    <div class="span12">
      <h1>Edit Experiment</h1>
    </div>
  </div>
  <div class="row banner">
    <div class="span12">
      <%= form_for @experiment, :url => { :action => "update" } do |f| %>
        <p>
          <%= f.label :label %>
          <%= f.text_field :label %>
        </p>
        <p>
          <%= f.button :class => 'btn btn-primary' %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/experiments/show.html.erb
<div class="content show-comparison-experiment">
  <div class="row">
    <div class="span6">
      <div class="row banner">
        <div class="span6"><h2>Comparison:</h2></div>
      </div>
      <div class="row">
        <div class="span2"><h4>state:</h4></div>
        <div class="span4"><h3><%= @comparison.state %></h3></div>
      </div>
      <div class="row">
        <div class="span2"><h4>species:</h4></div>
        <div class="span4"><h3><%= @comparison.species %></h3></div>
      </div>
    </div>
    <div class="span6">
      <div class="row banner">
        <div class="span6"><h2>Experiment:</h2></div>
      </div>
      <div class="row">
        <div class="span2"><h4>label:</h4></div>
        <div class="span4"><h3><%= @experiment.label %></h3></div>
      </div>
      <div class="row">
        <div class="span2"><h4>genes identified:</h4></div>
        <div class="span4">
          <h3><%= @experiment.identified %> <small>total</small></h3>
          <h3><%= @experiment.identified(:up) %> <small>up regulated</small></h3>
          <h3><%= @experiment.identified(:down) %> <small>down regulated</small></h3>
        </div>
      </div>
    </div>
  </div>
  <div class="row banner">
    <div class="span6">
      <h2>Genes:</h2>
    </div>
    <div class="span6 filter">
      filter by: <a href="#filter-experiments-modal" data-toggle="modal"><span class="label label-info">regulation</span></a>
    </div>
  </div>
  <div class="row">
    <div class="span12">
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th width="2%"></th>
            <th><%= sortable_col :name %></th>
            <th><%= sortable_col :chromosome %></th>
            <th><%= sortable_col :beg_site, 'begin site' %></th>
            <th><%= sortable_col :end_site %></th>
            <th><%= sortable_col :regulation %></th>
            <th><%= sortable_col :num_factors, 'factors discovered' %></th>
          </tr>
        </thead>
        <tbody>
          <% @genes.each do |gene| %>
            <tr>
              <td width="2%"><a class="edit" href="<%= edit_gene_path gene %>"><i class="icon-edit"></i></td>
              <td><%= link_to(gene.name, comparison_experiment_gene_path(@comparison, @experiment, gene)) %></td>
              <td><%= gene.chromosome %></td>
              <td><%= gene.beg_site %></td>
              <td><%= gene.end_site %></td>
              <td><%= gene.regulation %></td>
              <td><%= gene.num_factors %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div id="filter-experiments-modal" class="modal hide fade">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>Filter</h3>
  </div>
  <div class="modal-body">
    <form action="" class="form-horizontal" method="get">
      <fieldset>
        <div class="control-group">
          <%= label_tag :regulation, 'by regulation', :class => 'control-label' %>
          <div class="controls">
            <select id="regulation" name="regulation" class="span2">
              <option value="up">up</option>
              <option value="down">down</option>
            </select>
          </div>
        </div>
      </fieldset>
    </form>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn btn-primary">Filter</a>
    <a href="#" class="btn" data-dismiss="modal">Cancel</a>
  </div>
</div>