config/routes.rb
Tooltime::Application.routes.draw do
  # misc routes
  get 'main/index'
  
  # analytics
  get "gene_search/index"
  get 'gene_search/search'
  get "popular_factors/index"
  get "popular_factors/search"
  get "popular_factors/results"
  
  # data uploading
  post  'data/upload'
  match "/data/status/:job_id" => "data#status"
  
  # browse comparisons
  resources :comparisons do
    resources :experiments do
      resources :genes, :only => [:show], :controller => 'browse_genes' do
        resources :regulatory_elements, :only => [:show], :controller => 'browse_regulatory_elements'
      end
    end
  end
  
  # db summary: transcription factors
  resources :transcription_factors

  # db summary: genes
  resources :genes

  # db summary: regulatory elements
  resources :regulatory_elements
  
  # main page
  root :to => 'main#index'
end

app/models/regulatory_element.rb
class RegulatoryElement < ActiveRecord::Base
  belongs_to :gene
  has_and_belongs_to_many :pages
  has_and_belongs_to_many :transcription_factors
  
  validates_uniqueness_of :gene_id, :scope => [:beg, :len, :sns, :model]
  
  def self.all_senses
    self.select(:sns).uniq.map(&:sns)
  end
  
  def similar
    RegulatoryElement.where('id != ?', self.id).where(:gene_id => self.gene_id, :beg => self.beg, :sns => self.sns, :len => (self.len - 1)..(self.len + 1))
  end
end

app/controllers/regulatory_elements_controller.rb
class RegulatoryElementsController < ApplicationController
   def index
      @regulatory_elements = sorted_collection(RegulatoryElement.paginate(:page => params[:page], :per_page => 100))
   end
   
  def show 
    @regulatory_element = RegulatoryElement.find(params[:id])  
  end
  
  def edit
    @regulatory_element = RegulatoryElement.find(params[:id])
  end
  
  def update
    regulatory_element = RegulatoryElement.find(params[:id])
    regulatory_element.update_attributes(params[:regulatory_element])
    flash[:notice] = 'Regulatory Element updated successfully.'
    redirect_to regulatory_element
  end
end

app/views/regulatory_elements/edit.html.erb
<div class="content edit-comparison">
  <div class="row banner">
    <div class="span12">
      <h1>Edit Regulatory Element</h1>
    </div>
  </div>
  <div class="row banner">
    <div class="span12">
      <%= form_for @regulatory_element do |f| %>
        <p>
          <%= f.label :sequence %>
          <%= f.text_field :sequence %>
        </p>
        <p>
          <%= f.label :beginning %>
          <%= f.text_field :beg %>
        </p>
         <p>
          <%= f.label :length %>
          <%= f.text_field :len %>
        </p>
         <p>
          <%= f.label :sense %>
          <%= f.text_field :sns %>
        </p>
        <p>
          <%= f.label :la %>
          <%= f.text_field :la %>
        </p>
        <p>
          <%= f.label :la_slash %>
          <%= f.text_field :la_slash %>
        </p>
        <p>
          <%= f.label :lq %>
          <%= f.text_field :lq %>
        </p>
        <p>
          <%= f.label :ld %>
          <%= f.text_field :ld %>
        </p>
        <p>
          <%= f.label :ppv %>
          <%= f.text_field :ppv %>
        </p>
        <p>
          <%= f.button :class => 'btn btn-primary' %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/regulatory_elements/index.html.erb
<div class="content">  
   <div class="row banner">
     <div class="span12"><h1>Regulatory Elements</h1></div>
   </div>
   <div class="row">
   <div class="span12">
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th></th>
          <th><%= sortable_col :sequence %></th>
          <th><%= sortable_col :beg, 'begin site' %></th>
          <th><%= sortable_col :len, 'length'  %></th>
          <th><%= sortable_col :sns, 'direction' %></th>
          <th><%= sortable_col :model %></th>
          <th><%= sortable_col :la %></th>
          <th><%= sortable_col :la_slash, 'la /' %></th>
          <th><%= sortable_col :lq %></th>
          <th><%= sortable_col :ld %></th>
          <th><%= sortable_col :ppv %></th>
        </tr>
      </thead>
      <tbody>
        <% @regulatory_elements.each do |regulatory_element| %>
          <tr>
            <td><a class="edit" href="<%= edit_regulatory_element_path regulatory_element %>"><i class="icon-edit"></i></a></td>
            <td><%= link_to(regulatory_element.sequence, regulatory_element) %></td>
            <td><%= regulatory_element.beg %></td>
            <td><%= regulatory_element.len %></td>
            <td><%= regulatory_element.sns %></td>
            <td><%= regulatory_element.model %></td>
            <td><%= regulatory_element.la %></td>
            <td><%= regulatory_element.la_slash %></td>
            <td><%= regulatory_element.lq %></td>
            <td><%= regulatory_element.ld %></td>
            <td><%= regulatory_element.ppv %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @regulatory_elements %>
  </div>
</div>
</div>

app/views/regulatory_elements/show.html.erb
<div class="content show-gene">
  <div class="row">
    <div class="span2"><h4>Regulatory Element:</h4></div>
    <div class="span10"><h3><%= @regulatory_element.sequence %></h3></div>
  </div>
  <div class="row">
    <div class="span2"><h4>Begin Site:</h4></div>
    <div class="span10"><h3><%= @regulatory_element.beg %></h3></div>
  </div>
  <div class="row">
    <div class="span2"><h4>Length:</h4></div>
    <div class="span10"><h3><%= @regulatory_element.len %></h3></div>
  </div>
  <div class="row">
    <div class="span2"><h4>Sense:</h4></div>
    <div class="span10"><h3><%= @regulatory_element.sns %></h3></div>
  </div>
  <div class="row">
    <div class="span2"><h4>La:</h4></div>
    <div class="span10"><h3><%= @regulatory_element.la %></h3></div>
  </div>
  <div class="row">
    <div class="span2"><h4>La /:</h4></div>
    <div class="span10"><h3><%= @regulatory_element.la_slash %></h3></div>
  </div>
  <div class="row">
    <div class="span2"><h4>Lq:</h4></div>
    <div class="span10"><h3><%= @regulatory_element.lq %></h3></div>
  </div>
  <div class="row">
    <div class="span2"><h4>Ld:</h4></div>
    <div class="span10"><h3><%= @regulatory_element.ld %></h3></div>
  </div>
  <div class="row">
    <div class="span2"><h4>PPV:</h4></div>
    <div class="span10"><h3><%= @regulatory_element.ppv %></h3></div>
  </div>
</div>