config/routes.rb
Tooltime::Application.routes.draw do
  # misc routes
  get 'main/index'
  
  # analytics
  get "gene_search/index"
  get 'gene_search/search'
  get "popular_factors/index"
  get "popular_factors/search"
  get "popular_factors/results"
  
  # data uploading
  post  'data/upload'
  match "/data/status/:job_id" => "data#status"
  
  # browse comparisons
  resources :comparisons do
    resources :experiments do
      resources :genes, :only => [:show], :controller => 'browse_genes' do
        resources :regulatory_elements, :only => [:show], :controller => 'browse_regulatory_elements'
      end
    end
  end
  
  # db summary: transcription factors
  resources :transcription_factors

  # db summary: genes
  resources :genes

  # db summary: regulatory elements
  resources :regulatory_elements
  
  # main page
  root :to => 'main#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Team ToolTime</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="https://wiki.csc.calpoly.edu/366-Winter2012/wiki/TeamToolTime">Team ToolTime</a>
      <ul class="nav">
        <li class="home"><a href="/"><i class="icon-home icon-white"></i>Home</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#database-manipulation-menu">
            <i class="icon-plus-sign icon-white"></i>Database Manipulation
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">            
            <li><a href="#bulk-uploader-modal" data-toggle="modal">Upload Data</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#database-summary-menu">
            <i class="icon-file icon-white"></i>Database Summary
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Genes", genes_path %></li>
            <li><a href= <%= regulatory_elements_path %>>Regulatory Elements</a></li>
            <li><a href= <%= transcription_factors_path %>>Transcription Factors</a></li>
          </ul>
        </li>
        <li class="browse-comparisons"><%= link_to '<i class="icon-th-list icon-white"></i>Browse Comparisons'.html_safe, comparisons_path %></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#analytics-menu">
            <i class="icon-list-alt icon-white"></i>Analytics
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Gene Search', gene_search_index_path %></li>
            <li><%= link_to 'Popular Factors', popular_factors_index_path %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>
<div id="bulk-uploader-modal" class="modal hide fade">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>Upload Data</h3>
  </div>
  <div class="modal-body">
    <%= form_tag(data_upload_path, :multipart => true, :class => 'form-horizontal') do %>
      <fieldset>
        <p>There should be 3 related .csv files for every set of gene data.</p>
        <div class="control-group">
          <%= label_tag :data, 'select your files', :class => 'control-label' %>
          <div class="controls">
            <%= file_field_tag 'data[]', :multiple => 'multiple', :accept => 'text/csv' %>
          </div>
        </div>
      </fieldset>
    <% end %>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn btn-primary">Upload</a>
    <a href="#" class="btn" data-dismiss="modal">Cancel</a>
  </div>
</div>
<div class="container">
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <a class="close" data-dismiss="alert">×</a>
      <%= flash[:notice] %>
    </div>
  <% end %>
  <%= yield %>
</div>
</body>
</html>